### ISSUE TITLE
Allow recursive searching for files in a directory

### ISSUE THREAD

**Issue by LefterisJP** [theendlessriver13/double-indent#18]
It would be really cool if the tool could work with directories as input and recursively search them for files

**Comment by theendlessriver13** [comment]
Hey, thanks for the question!

You can easily achieve this by using `double-indent` within the [pre-commit.com](https://pre-commit.com/) framework. See the [readme](https://github.com/theendlessriver13/double-indent#pre-commit-hook) for setup instructions.

If you don't want to use `pre-commit`, you can emulate the behavior by running `double-indent` on a folder (in the example `tests`) in a git-repo only taking checked in files into account:

```bash
git ls-files | grep -E "tests.+\.py$" | xargs double-indent
```

...or if it's not a git repo or also want to apply `double-indent` to files not checked in:
```bash
find tests/ -name "*.py" | xargs double-indent
```

I hope this helps and solves your issue?

**Comment by LefterisJP** [comment]
Hey @theendlessriver13!

Thanks for the quick answer. Unfortunately in our project we don't use the pre-commit framework. But this would be really trivial to implement and I took the liberty to add the functionality in a PR. I tested it and it works fine for my project.

Would you be open to accepting it as a PR?

Using find and xargs is also possible but why not have it work from inside double-indent directly? It's easy!
